-- UNION RP - Schema base (normalizado, metadata)

CREATE TABLE IF NOT EXISTS characters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  birthdate DATE NULL,
  gender VARCHAR(16) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_character_name (name)
);

CREATE TABLE IF NOT EXISTS inventories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  owner_type VARCHAR(32) NOT NULL, -- character, vehicle, stash
  owner_id BIGINT UNSIGNED NOT NULL,
  slot_limit INT NOT NULL,
  weight_limit DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  label VARCHAR(64) NOT NULL,
  weight DECIMAL(10,2) NOT NULL,
  stack_limit INT NOT NULL DEFAULT 1,
  metadata JSON NULL
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  inventory_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (inventory_id) REFERENCES inventories(id),
  FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS world_memory (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  region_code VARCHAR(64) NOT NULL,
  heat_score DECIMAL(10,2) NOT NULL DEFAULT 0,
  last_event_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_region (region_code)
);

CREATE TABLE IF NOT EXISTS world_narratives (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  region_code VARCHAR(64) NOT NULL,
  narrative_key VARCHAR(64) NOT NULL,
  intensity DECIMAL(10,2) NOT NULL DEFAULT 0,
  expires_at TIMESTAMP NULL,
  metadata JSON NULL
);

CREATE TABLE IF NOT EXISTS autobalance_rules (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  activity_key VARCHAR(64) NOT NULL,
  multiplier DECIMAL(10,4) NOT NULL DEFAULT 1,
  last_adjustment TIMESTAMP NULL,
  UNIQUE KEY uniq_activity (activity_key)
);

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  job_key VARCHAR(64) NOT NULL,
  label VARCHAR(64) NOT NULL,
  legal TINYINT(1) NOT NULL DEFAULT 1,
  metadata JSON NULL,
  UNIQUE KEY uniq_job_key (job_key)
);

CREATE TABLE IF NOT EXISTS job_assignments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  character_id BIGINT UNSIGNED NOT NULL,
  job_id BIGINT UNSIGNED NOT NULL,
  on_duty TINYINT(1) NOT NULL DEFAULT 0,
  grade INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (character_id) REFERENCES characters(id),
  FOREIGN KEY (job_id) REFERENCES jobs(id)
);

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  owner_character_id BIGINT UNSIGNED NULL,
  plate VARCHAR(16) NOT NULL,
  model VARCHAR(64) NOT NULL,
  metadata JSON NULL,
  UNIQUE KEY uniq_plate (plate)
);

CREATE TABLE IF NOT EXISTS vehicle_condition (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  vehicle_id BIGINT UNSIGNED NOT NULL,
  engine_health DECIMAL(5,2) NOT NULL DEFAULT 100,
  body_health DECIMAL(5,2) NOT NULL DEFAULT 100,
  tire_count INT NOT NULL DEFAULT 4,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

CREATE TABLE IF NOT EXISTS phone_devices (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id BIGINT UNSIGNED NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  metadata JSON NULL,
  UNIQUE KEY uniq_phone_number (phone_number)
);

CREATE TABLE IF NOT EXISTS radio_devices (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id BIGINT UNSIGNED NOT NULL,
  frequency VARCHAR(16) NOT NULL,
  encrypted TINYINT(1) NOT NULL DEFAULT 0,
  metadata JSON NULL
);

CREATE TABLE IF NOT EXISTS medical_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  character_id BIGINT UNSIGNED NOT NULL,
  last_treatment TIMESTAMP NULL,
  metadata JSON NULL,
  FOREIGN KEY (character_id) REFERENCES characters(id)
);

CREATE TABLE IF NOT EXISTS economy_ledger (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  character_id BIGINT UNSIGNED NULL,
  entry_type VARCHAR(32) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
